version: '2.4'
services:
  yolov5:
    image: yolov5
    privileged: true
    build:
      context: ../../../src/yolov5/docker/ycbv_segmentation_service
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../../src/yolov5:/root/yolo
    environment:
      - ROS_MASTER_URI=http://hsrb.local:11311
      - ROS_IP=10.0.0.232
      - ROS_HOSTNAME=rocco
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source catkin_ws/devel/setup.bash;
                      python ./yolo/detect_ros_seg.py --weights ./yolo/yolov5_ycbv_weights.pt --data ./yolo/data/ycbv.yaml --camera-topic "$$(rosparam get /pose_estimator/color_topic)""
    stdin_open: true
    tty: true 
