version: '2.4'
services:
  motion:
    image: motion
    build:
      context: ../../src/motion_public/docker
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../../src/motion_public:/root/motion:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source /opt/pal/gallium/setup.bash; source catkin_ws/devel/setup.bash;
             while true; do sleep 1000; done"        
    stdin_open: true
    tty: true