version: '2.4'
services:
  pointing_gesture_recognition:
    image: pointing_gesture_recognition
    privileged: true
    build:
      context: ../../../src/pointing_gesture_recognition/docker
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "../../../src/pointing_gesture_recognition:/root/pointing_gesture_recognition:rw"
      - "../../../data/datasets:/root/pointing_gesture_recognition/datasets:rw"
      - ../../../config:/root/config
    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - DATASET=${DATASET}
    command: bash -c "source catkin_ws/devel/setup.bash;
                      python ./pointing_gesture_recognition/pointing_detector.py \
                          --color-topic '$$(rosparam get /pose_estimator/color_topic)' \
                          --depth-topic '$$(rosparam get /pose_estimator/depth_topic)' "
    stdin_open: true
    tty: true 
